### PR TITLE
Release 6.0

### PR DESCRIPTION
**Pull request by M0rgan01**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Release 6.0.0
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | Please perform a full testing of the module as this is a new major release.

### CODE REVIEW

**Comment by leemyongpakvn** [comment]
@M0rgan01 @kpodemski  I made PR #175 mostly for PR #177 that contains many BCs. If you release V6 this time, we must bump to V7 after PR 177. :rocket:
Another option Release v5.04 without PR 175 ;)

**Comment by kpodemski** [comment]
@leemyongpakvn I think we should wait for your PR

**Review by kpodemski — CHANGES_REQUESTED** [review]
Let's wait for @leemyongpakvn since he put a lot of effort into his PR :)

https://github.com/PrestaShop/productcomments/pull/177

**Comment by leemyongpakvn** [comment]
@M0rgan01 PR 177 was reviewed by @matks and @kpodemski. I answered all questions and applied some suggestions so it's their turn now. And I'm pretty sure that **matks** don't like bumping to v7.0.0 much ;)

**Review by matks — APPROVED** [review]
Let's go 💪

**Review by tleon — APPROVED** [review]

**Pull request merged**
