### PR TITLE
Fix: update product listing ratings on updateProduct event

### PR DESCRIPTION
**Pull request by tblivet**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Update the ratings of the product list when the `updatedProduct` event is triggered on the product page.
| Type?         | bug fix / improvement
| BC breaks?    | no
| Deprecations? | 
| Fixed ticket? | 
| How to test?  | You need a product with combinations and accessories (related products), and these accessories must have reviews.  ⬇️

**Before:**
When a combination changes, all star ratings are set to 1.

https://github.com/PrestaShop/productcomments/assets/110676325/c8289f9a-1247-4e06-a080-fe5552eaba16

**After:**
When a combination changes, all star ratings are refreshed.

https://github.com/PrestaShop/productcomments/assets/110676325/43a11166-50c3-4765-8497-d7963c95b534

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hello @tblivet!

This is your first pull request on the PrestaShop project. Thank you, and welcome to this Open Source community!

**Review by ga-devfront — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Comment by pawelkierklo** [comment]
If products are loaded using AJAX and they contain a rating, why does JavaScript need to reload them?

**Review by florine2623 — COMMENTED** [review]
Hello @tblivet ,

Thanks for the PR !

After installing it and testing it, I still have the old behavior :


https://github.com/PrestaShop/productcomments/assets/16019289/6d37bb86-7f1f-4dea-ac61-af94e4b9ea1d



Am I missing something ?
Thanks!

**Comment by tblivet** [comment]
Hi @pawelkierklo!
Yes, the product templates are reloaded, but without executing JS, the stars won't be re-rendered.

Hi @florine2623, it's strange. Have you tried to reset the module in the BO and then redo the test?

**Review by florine2623 — APPROVED** [review]
Hello @tblivet ,

I might have some issues with the installation of the PR the first time I tested it.

Tested with one/multiple related products, tested with/without comments on these related products, tested with deleted the product's reviews.

It is QA ✅ 
Thanks!

**Pull request merged**
