### PR TITLE
Remove useless v5 upgrade file, there was no v5 released

### PR DESCRIPTION
**Pull request by jf-viguier**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Remove this wrong and useless upgrade file, there is no 5.0.0 version (the 4.0.0 has been renamed)
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/24814
| How to test?  | no way, no 5.0 version

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
@jf-viguier Could you move this commit in the another PR ? It will be more uniform.

**Comment by jf-viguier** [comment]
thanks Franck

**Comment by jf-viguier** [comment]
> Could you move this commit in the another PR ? It will be more uniform.
Why ? I've posted an issue, it's the rule.

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
@PrestaShop/prestashop-maintainers I'll need access guys 🙏

**Comment by matks** [comment]
> @PrestaShop/prestashop-maintainers I'll need access guys 🙏

Sorry, some repositories access settings are a mess. Fixed ✅

**Review by matks — COMMENTED** [review]
Hello, I agree that this upgrade file is useless because there was no v5 release.

However, is the right solution to _remove_ this file or to _modify it_ to become `upgrade/install-4.0.0.php` ?

I look at the content of the productcomments module, I don't understand why the file `upgrade/install-5.0.0.php` modifies `PRODUCT_COMMENTS_PAGE_COMMENTS_NB ` constant. I have no idea 😅 .

However I see the constant `PRODUCT_COMMENTS_USEFULNESS ` is being used. So maybe transform `upgrade/install-5.0.0.php` into `upgrade/install-4.0.0.php` makes sense.

We can also ask @jolelievre who submitted the PR https://github.com/PrestaShop/productcomments/pull/26 that added these files to shine some light on this mystery 🕵️

**Comment by jf-viguier** [comment]
@matks I've done a pr for version 4 upgrade: new hooks and conf values

**Comment by kpodemski** [comment]
Thx @jf-viguier

**Pull request merged**
