### PR TITLE
Release 5.0.0

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Release 5.0.0
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | N/A
| How to test?  | Release Test

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by florine2623** [comment]
Hello @Progi1984 ,

With this PR I encounter an issue, on the product page, the product comment block is displayed in the newsletter block : **NOK**
With review :
Screenshot 2021-11-17 at 15 05 18
Without review :
Screenshot 2021-11-17 at 15 10 10


Without PR : **OK**
Screenshot 2021-11-17 at 15 05 03

Could you take a look ? Thanks you !

**Comment by Progi1984** [comment]
@florine2623 The bugfix is in the PR #119

**Comment by Progi1984** [comment]
@florine2623 The PR #119 is merged.

**Comment by florine2623** [comment]
Thanks @Progi1984 ! It is all good for me ✅

**Pull request merged**
