### PR TITLE
Listening event on product refresh to construct stars again

### PR DESCRIPTION
**Pull request by NeOMakinG**
Needs to be merged before https://github.com/PrestaShop/PrestaShop/pull/17020

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Listening event on product refresh to construct stars again
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes partially https://github.com/PrestaShop/PrestaShop/issues/15184
| How to test?  | You need to activate review on products, send one review at least on a product, go on product page and change quantity for example or combination, stars needs to stay, while before stars were disappearing !

### CODE REVIEW

**Comment by matks** [comment]
@NeOMakinG can you provide a better PR title please ? 😄

**Comment by matks** [comment]
@NeOMakinG I added the table in PR description. Can you tell us how to test ? What part of the issue is solved by this PR ? Do the 2 PRs https://github.com/PrestaShop/PrestaShop/pull/17020 and this one need to be tested together ?

**Comment by NeOMakinG** [comment]
Yes the 2 PRs needs to be tested together, this one is receipting an event to refresh, the other is sending the event, since the refresh call is done in core while the stars are init in this module...

Updated the desc to test

**Comment by SD1982** [comment]
the pull request correctly fix the issue. Thanks @NeOMakinG

**Comment by matks** [comment]
Thank you @NeOMakinG

**Pull request merged**
