### PR TITLE
Replace deprecated jquery methods.

### PR DESCRIPTION
**Pull request by lmeyer1**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Replace deprecated jquery methods with current.
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | I didn't find a specific issue, but it seems working out jquery deprecations is ongoing (e.g. #15943)
| How to test?  | In dev mode, jqmigrate no longer complains, also, verify that module work as expected (it's about click actions modifications)

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by NeOMakinG** [comment]
As it's about click actions, I think we should push it to the QA

**Comment by sarahdib** [comment]
hello @lmeyer1 

Thank you for this PR.

I check this but nothing change in console.
Capture d’écran 2021-07-19 à 14 00 18

Could you check ,

Thank you

**Comment by lmeyer1** [comment]
@sarahdib
I only fixed the display on a product page. There shouldn't display any warnings anymore.
On which page do these warnings display in console?

**Comment by lmeyer1** [comment]
@sarahdib 
I'm conscient, that I did not perform a in-depth review of all the code, that why I left `[WIP]` in the title, and there are probably remaining compatibility issues.
But I cannot understand, that on your side there are still as many notices. I can assure you, that on the product page, on my side, there is no deprecation message related to `productcomments` remaining anymore.
I don't have time to invest, neither to understand what the reason is behind this difference of behavior, nor to compete the work by reviewing the complete Javascript codebase.
Therefore, I prefer to close this issue, than to continue and endless revision process.

**Pull request closed without merging**
