### PR TITLE
Make rating mandatory

### PR DESCRIPTION
**Pull request by leemyongpakvn**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Make rating mandatory. Please check detail in related issue.
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#26001
| How to test?  | Apply PR changes then check to make sure that Review with Empty Title, Name, Content or not chosen Rating won't be accepted.<br/> (Don't forget to use a clean dev branch, FO - clear Browser cache, BO - clear PS cache before testing ;)

### CODE REVIEW

**Review by matthieu-rolland — COMMENTED** [review]
thank you for taking care of this 👍 

there is no backend validation for this rating mechanism ?

**Comment by leemyongpakvn** [comment]
@matthieu-rolland No, this PR just add ratingChosen front-end validation like Review's title, author and content in the same `function validateFormData`. Furthermore, `ratingChosen` variable is set programmatically (not by a user input) and won't be saved to DB, so there is no need for back-end validation.

**Review by mflasquin — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @leemyongpakvn ,

On classic theme it works like expected.

Screenshot 2024-01-23 at 14 27 42

Although, I think the color should be the same red as the red in the message alert : 
Screenshot 2024-01-23 at 14 34 09

Also, it should the vertically alight to the right.

But on hummingbird, it doesn't work.

Could you make it compatible for both themes ?

https://github.com/PrestaShop/productcomments/assets/16019289/e514ce71-c00a-4628-82bd-0190f0a9dc78

Could you check ? :)
Thanks!

**Comment by leemyongpakvn** [comment]
@florine2623 `ratingNotChosen` message's Color and Alignment are changed following your suggestion. An implementation of this PR for hummingbird theme is also added https://github.com/PrestaShop/hummingbird/pull/577.

**Comment by paulnoelcholot** [comment]
Hello  @leemyongpakvn,

I tested your PR on classic theme and hummingbird and I got this : 
image
image

Can you check it please?

Thanks!

**Comment by leemyongpakvn** [comment]
@paulnoelcholot Did you remember to apply _FO - clear Browser cache, BO - clear PS cache before testing_ ?

**Comment by AureRita** [comment]
Hi @leemyongpakvn 

Thank you for your PR, I tested it and it seems to works as you can see : 

[recording(79).webm](https://github.com/PrestaShop/productcomments/assets/100699445/df057217-65ea-47ba-92e3-60feb70491fd)

Unfortunately, you can also see that if you clic again on "Write your review" after put none rate on the product, you still have "* Please choose a rating for your review." 

Can you check it ? 

Thank you

**Comment by leemyongpakvn** [comment]
@AureRita I saw and fixed it with my 5th commit. Please check again.

**Comment by AureRita** [comment]
Thank you for your changes, now the problem is on the other way, when you put a rate, press send (to have the message that is hidden) close the modal and want to write a new review without rate, you didn't have the error message, as you can see : 

[recording(81).webm](https://github.com/PrestaShop/productcomments/assets/100699445/21f1f626-231e-4ec6-bf1a-9431f159acd9)

Waiting for your next changes :rocket: 

Thank you

**Comment by leemyongpakvn** [comment]
@AureRita In the scenario: _when you put a rate, **press send** OR just close the modal **without send**, then try to make a new review without rate_ it means you are already aware of the need to put a rate. So it can be a nuisance when keeping the warning message there :) Wdyt @MatShir  ?

**Review by matks — APPROVED** [review]
Code is good for me 👍

**Comment by leemyongpakvn** [comment]
@AureRita As discussed in Slack, Krystian agreed with you, so I have changed the code following your opinion. Please check again.

**Comment by MatShir** [comment]
@leemyongpakvn thanks for making the effort 🤗 
Late answer (sorry), Consistent error message for a better UX is always appreciated

**Review by AureRita — APPROVED** [review]
Hi @leemyongpakvn 

Thank you for your PR, I tested it and it seems to works as you can see : 

[recording(91).webm](https://github.com/PrestaShop/productcomments/assets/100699445/816c0963-bf68-49bc-bc33-0bc38bcab0ab)

Because the PR seems to works as expected on develop and 8.1.x, It's QA :heavy_check_mark: 

Thank you for all your best efforts ! :rocket:

**Comment by leemyongpakvn** [comment]
Thanks to all ;)

**Pull request merged**
