### PR TITLE
Align rating to the left on product list

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | The rating is not really aligned on product of product list
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#27252.
| How to test?  | You should test this pr with https://github.com/PrestaShop/PrestaShop/pull/27387, this one is just about this element to be aligned to the left of the product

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Review by marwachelly — CHANGES_REQUESTED** [review]
Hello, 

I tested this PR with PrestaShop/PrestaShop#27387. The grade is now displayed in the Product list page but the following error exists 
image
I noticed also the following error when I run the command npm install 
image
Could you please check ? 

Thanks,

**Comment by NeOMakinG** [comment]
@marwachelly The problem with `npm i` is not linked to the PR at all

The left alignment is fixed on my side, do you've some cache issues?

**Comment by marwachelly** [comment]
> @marwachelly The problem with `npm i` is not linked to the PR at all
> 
> The left alignment is fixed on my side, do you've some cache issues?

@NeOMakinG You are right. It seems that it was a cache issue. Thank you for the fixe! 
https://watch.screencastify.com/v/axqDIA9TxLhIi3wo5j0P

**Review by marwachelly — APPROVED** [review]
PR is ok. Issue is fixed. Thanks @NeOMakinG

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @marwachelly

**Pull request merged**
