### PR TITLE
Fix the remaining issue of Github update_release_draft

### PR DESCRIPTION
**Pull request by leemyongpakvn**
Test Morgan's 2nd scenario which will requires only one-line-change in Organization Build& Release.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | update_release_draft of Organizaion Build & Release failed when Release new version. zip step is fixed by PR 181, but PublishToGitHubRelease step is still failed due to wrong path.
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#33278
| How to test?  | Github Build update_release_draft success

### CODE REVIEW

**Comment by M0rgan01** [comment]
@leemyongpakvn I think of 3 scenarios:
- We are revert the changes that were made in https://github.com/PrestaShop/productcomments/pull/181, merge https://github.com/PrestaShop/.github/pull/9 and then on a 6.0.2 tested that everything is fine.
- We make the same modifications on the PR https://github.com/PrestaShop/.github/pull/9, we merge this PR and we tested it on a 6.0.2 before merging https://github.com/PrestaShop/.github/pull/9.
- We keep this PR like this, we adjust the https://github.com/PrestaShop/.github/pull/9 to have the same changes, we merge this PR and we test on a 6.0.2 before merging https://github.com/PrestaShop/.github/pull/9.

**Comment by leemyongpakvn** [comment]
@M0rgan01 The first scenario is out of our agreement yesterday: test locally then apply globally. So I choose the second scenario. If the second scenario fails, we will try the third scenario.

**Comment by matks** [comment]
@leemyongpakvn @M0rgan01 great to see you two working together on this topic

So we expect a 6.0.2 with the fixed GH Action is that right?

**Comment by M0rgan01** [comment]
yes @matks that's it

**Pull request merged**
