### PR TITLE
Test Organization build-release.yml in productcomments repo

### PR DESCRIPTION
**Pull request by leemyongpakvn**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | update_release_draft of Organizaion Build & Release failed when Release new version. We need test it separately in this repository.
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#33728
| How to test?  | Github Build update_release_draft succeed in Release 6.0.1

### CODE REVIEW

**Comment by matks** [comment]
So you replace the Github action global by a custom one. What are the changes that you introduce and will fix the problem?

**Comment by leemyongpakvn** [comment]
If we make changes directly in https://github.com/PrestaShop/.github/blob/master/.github/workflows/build-release.yml, it will affects all modules. So I choose copying Organization build-release.yml content to this repo for safety (not a custom one, it is an exact copy for testing). 
I doubt this commit https://github.com/PrestaShop/.github/commit/aba1484b021ac5a11f23c92bbc4ef1d31808bdd1
or outdated [actions/upload-release-asset@v1.0.2](https://github.com/actions/upload-release-asset) raises the update_release_draft issue.
And we need an environment to test it in action, right?

**Comment by Hlavtox** [comment]
@leemyongpakvn The build script is broken in all module repositories and themes, so why don't we apply it globally?

**Comment by leemyongpakvn** [comment]
@Hlavtox For safety, once we fix the issue locally in this repo, we will apply it globally.

**Comment by Hlavtox** [comment]
@leemyongpakvn OK brother, sounds good. :-)

**Comment by leemyongpakvn** [comment]
@M0rgan01 I tried to remove `${{ github.event.repository.name }}` at line 24 in **deploy** step. If it does not work, we can try to remove `cd ${{ github.event.repository.name }}` at line 40 in **update_release_draft** step

**Review by M0rgan01 — APPROVED** [review]
Let's see what it gives

**Comment by matks** [comment]
> If we make changes directly in https://github.com/PrestaShop/.github/blob/master/.github/workflows/build-release.yml, it will affects all modules. So I choose copying Organization build-release.yml content to this repo for safety (not a custom one, it is an exact copy for testing).

Good approach 👍

**Comment by M0rgan01** [comment]
@leemyongpakvn `asset_path: ./${{ github.event.repository.name }}/${{ github.event.repository.name }}.zip` must also be replaced by  `asset_path: ./${{ github.event.repository.name }}.zip`

**Comment by leemyongpakvn** [comment]
I don't think so. I think old `cd ${{ github.event.repository.name }}` is correct since https://github.com/PrestaShop/contactform/releases/tag/v4.4.1 and https://github.com/PrestaShop/ps_languageselector/releases/tag/v2.1.3 were built correctly in March, while https://github.com/PrestaShop/ps_linklist/releases/tag/v6.0.3 on 23 June need manual change - 10 days after actions/upload-release-asset@v1.0.2 outdated
as you can see in the recent actions Annotations: https://github.com/PrestaShop/productcomments/actions/runs/6000817427

**Comment by leemyongpakvn** [comment]
We have clearer information when testing locally in productcomments repo at
https://github.com/PrestaShop/productcomments/actions/runs/6000817427 Annotations:
>
update_release_draft
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/upload-release-asset@v1.0.2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

**Comment by leemyongpakvn** [comment]
@M0rgan01 After carefully checking Actions of recent Releases of Native modules between March and June this year, I think you are right now ;) Unfortunately, the non-native module qualityassurance does not have BuildRelease workflow so we must continue testing on this repo. PR #184 is waiting.

**Pull request merged**
