### PR TITLE
Release 6.0.3

### PR DESCRIPTION
**Pull request by boherm**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Release 6.0.3
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  |

### CODE REVIEW

**Review by Hlavtox — APPROVED** [review]
Now all good. :-)))

**Review by florine2623 — COMMENTED** [review]
Hello @boherm ,

Upgrade to v6.0.3 went well.
Configuration of module is broken when Debug mode is enabled.

Screenshot 2024-04-02 at 17 05 53


https://github.com/PrestaShop/productcomments/assets/16019289/af091e37-07a7-492b-a9ec-939ecbc27b61

Could you check ?

**Comment by leemyongpakva** [comment]
@florine2623 I think it is a well-known issue, old SF configs in var/cache does not contain newly added service. You can solve it by applying _BO > Performance > Clear Cache_ via Web browser, or running `rm -rf /var/cache` via Terminal.

**Review by florine2623 — APPROVED** [review]
Hello @boherm ,

Tested the following :
https://github.com/PrestaShop/productcomments/pull/144
https://github.com/PrestaShop/productcomments/pull/190
https://github.com/PrestaShop/productcomments/pull/191
https://github.com/PrestaShop/productcomments/pull/193
https://github.com/PrestaShop/productcomments/pull/197
https://github.com/PrestaShop/productcomments/pull/198

LGTM ✅ 
Thanks!

**Comment by leemyongpakva** [comment]
Thanks @boherm and @florine2623

**Pull request merged**
