### PR TITLE
Fix typo in query

### PR DESCRIPTION
**Pull request by kpodemski**
nothing to comment here, in various scenarios `validate` value was empty

| Sponsor company  | impSolutions

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]
Damn, it was always empty right? Looks good to me, but I think we should wait for one more review before sending it to QA and merging

Can you provide a way to test it for the QA if it's needed ?

Thanks for your contribution !

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Ping @kpodemski

**Comment by kpodemski** [comment]
@NeOMakinG yes it was always empty, we found it while working on a customer store, hard to tell how to test, for us module didn't work at all, i mean, reviews were not retrieved on product lists

**Comment by NeOMakinG** [comment]
Thanks @kpodemski 

@PrestaShop/prestashop-core-developers do we need QA on this ? I don't think myself since it should'nt be working anyway, maybe the QA can just test the module globally?

**Comment by Progi1984** [comment]
@PrestaShop/qa-functional Do we need QA for this ?

**Comment by SimonGrn** [comment]
We can make some exploratory testing.

**Comment by Progi1984** [comment]
Thanks @kpodemski & @sarahdib

**Pull request merged**
