### PR TITLE
Fix js error since displayGDPRConsent

### LINKED ISSUE #26834: FO - Productcomments - The Grade and the comment are not displayed in the Product page
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After an upgrade of the module Productcomments, the grade & the comments are not displayed on the Product details page
image

It should be
image

### Expected behavior

_No response_

### Steps to reproduce

1. Go to FO > sign in
2. Go to FO > Product details page and write a comment
3. Go to BO > Module manager > productcomments & upgrade it to v5.0.0
4. Approve the review
5. go to FO > See product details page
6. NO comment displayed + no grade displayed

### PrestaShop version(s) where the bug happened

1.7.8.1, 1.7.8.2build1

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

productscomments v5.0.0

### PR DESCRIPTION
**Pull request by ghost**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Since adding displayGDPRConsent there is a js error
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#26834
| How to test?  | Check if comment and note are ok, try to add comment, checl also the display with quick views
| Sponsor company   | @Touxten

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by florine2623** [comment]
Hello @okom3pom ,

Thanks for your PR ! 
Looks good to me on the product page. Works as attended after au an upgrade.

You mentioned to check the QuickView. There is no productcomments element, is this the Wanted behavior : 
Screenshot 2021-12-15 at 15 51 34

Let me know :)

**Comment by okom3pom** [comment]
Hello @florine2623 wich version of PrestaShop ?

**Comment by okom3pom** [comment]
Ok i manage to reproduce it's not the PR : 

https://www.okom3pom.com/videos/product_comment.webm

When we clih a second time no reviews, it's an other issue

**Comment by florine2623** [comment]
Hello @okom3pom ,

Ok, noted. Feel free to ping me if you create a new PR for that issue :)
For now, this PR is QA approved ✅ 
Thanks!

**Comment by PierreRambaud** [comment]
Thank you @okom3pom and @florine2623

**Pull request merged**
