### PR TITLE
Renders author name with a link if it is a customer

### LINKED ISSUE #27089: Link to the customer page if the author is a customer
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

This feature request is related to the ProductComments module.

Original feature request from @vallka 

> Adding a link to the customer profile in BO - product comments lists (just like it was done recently in Orders list). This allows moderators to quickly navigate to comment author's profile - e.g. we use this feature to add royalty points to comments authors

### Describe the solution you'd like

Link to the profile page, if the author of the comment is a customer

### Alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Rework of https://github.com/PrestaShop/productcomments/pull/123
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#27089.
| How to test?  | Please indicate how to best verify that this PR is correct.

image

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by HanaRebaiQA** [comment]
Hello @kpodemski

**Comment by HanaRebaiQA** [comment]
Hello @kpodemski

**Comment by HanaRebaiQA** [comment]
Hello @kpodemski

**Comment by HanaRebaiQA** [comment]
Hello @kpodemski 

This PR is tested on PS1782 and PS178x 
But, it's blocked in develop branch cause of this issue [#27130](https://github.com/PrestaShop/PrestaShop/issues/27130) 
I will check again when the issue is fixed.

Thanks!

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @kpodemski 

I checked again this issue [#27130](https://github.com/PrestaShop/PrestaShop/issues/27130) which is fixed by the new version of `productcomments` on dev branch.
But, this PR still blocked by this one [#27119](https://github.com/PrestaShop/PrestaShop/issues/27119).
So, it will be tested again when the issue is fixed.

Thank you!

**Review by HanaRebaiQA — APPROVED** [review]
Hello @kpodemski 

To unblock the situation and be able to test the PR finally, i disable the `blockwishlist` module which caused by this issue [#27119](https://github.com/PrestaShop/PrestaShop/issues/27119)

So, i tested again on develop with `productcomments v5.0.1 `from dev branch.
I checked with multistore and different langauges.
image






https://user-images.githubusercontent.com/92912932/153388030-68715a9e-0b91-4f63-9dd9-07857ec0c7a5.mp4







https://user-images.githubusercontent.com/92912932/153387098-cb3d62e6-14f3-4285-9ef2-e52198148402.mp4





So, QA :heavy_check_mark: 

Thanks!

**Comment by Progi1984** [comment]
Thanks @kpodemski & @HanaRebaiQA

**Pull request merged**
