### PR TITLE
Change min compatibility & module version

### PR DESCRIPTION
**Pull request by tleon**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Since 6.0.3 introduced a big change regarding some symfony services, we decided to up the min version and release a 7.0.0 to avoid problems with the 1.7.7.x compatibility.
| Type?         | improvement 
| BC breaks?    | no
| Deprecations? | yes
| Issue | #35886
| How to test?  | upgrade the module on 1.7.8.x and upward is ok.

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Comment by leemyongpakva** [comment]
@tleon 1.7.7 need to be removed in https://github.com/PrestaShop/productcomments/blob/dev/.github/workflows/php.yml

**Comment by tleon** [comment]
> @tleon 1.7.7 need to be removed in https://github.com/PrestaShop/productcomments/blob/dev/.github/workflows/php.yml

I think I did already didn't I ? 
https://github.com/PrestaShop/productcomments/pull/204/files#diff-a73bb6555480a5ee79ae276a3f5d71a08fa316e09a4a8da7b643cf1e92c97df9L61
Or did I miss something else ?

**Comment by leemyongpakva** [comment]
@tleon Sorry, I checked the current file ;)

**Review by leemyongpakva — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Comment by florine2623** [comment]
@kpodemski indeed, this doesn't need manual testing as it's just version changes ^^

**Pull request merged**
