### PR TITLE
Update product-comments-list.tpl

### PR DESCRIPTION
**Pull request by Varindien**
Comments not displayed properly because of smarty parameter not beeing between double quote.

### CODE REVIEW

**Comment by sarjon** [comment]
Hi @Varindien, thanks for you contribution! :)

However, I don't see how previous syntax should be causing issues. I've checked the module and it seems comments are displayed properly. 

Can you give more context of then it doesn't work? :)

**Comment by PierreRambaud** [comment]
I change the target branch but yours need to be rebased

**Comment by Progi1984** [comment]
Ping @Varindien

**Comment by Varindien** [comment]
Hello,

Most of my project need to be converted to double quote instead of simple quote to display properly comments. i tried to figure out why. Maybe a server side configuration but dunno which one can impact this.

**Comment by Varindien** [comment]
Hello,

I gave a try to my dev environnement which now is under PHP 7.3 and this module with version 4.0.1. 
All is ok with this environnment.
i did not noticed this because i was using another module. 

It might be an issue with my previous environment. 🤔

**Pull request closed without merging**
