### PR TITLE
Simplify Average code

### PR DESCRIPTION
**Pull request by leemyongpakvn**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Replace SUM(pc.`grade`) / COUNT(pc.`grade`) by AVG(pc.`grade`) to simplify code
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#29357
| How to test?  | Please use productcomments module and create multiple customer reviews for products. Please then verify that the "average rating" on the front-office product page is correct: if a product received ratings 1/5 and 5/5 then the average should be 3/5

### CODE REVIEW

**Comment by leemyongpakvn** [comment]
There is a redundant open parenthesis at line 181 but I don't know how to Amend the commit.

**Review by matthieu-rolland — COMMENTED** [review]
Did you test it to be sure you get the same result ?

I ask because I've never seen usage of `AVG` without a `group by` or at least a `join` (which doesn't mean it's not possible, I've just not seen it before)

**Comment by leemyongpakvn** [comment]
@matthieu-rolland I already tested on my locahost, the same result and no error.

Here is a clear explanation of how `AVG` works in MariaDB - a successful fork of MySQL
https://www.mariadbtutorial.com/mariadb-aggregate-functions/mariadb-avg/
- First, ignore the null values.
- Then, divide the **sum of** all values by the **number of** values

`GROUP BY` or `JOIN` are optional in `AVG` syntax, in the simplest form we just need `SELECT AVG('field_name') FROM 'table_name'`, there are some examples at https://www.mysqltutorial.org/mysql-avg/

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
Hey @leemyongpakvn 

I've noticed there's no dedicated Issue for this PR. Could you create one? The change is ok 👍  I've checked the results, and they are the same.

**Comment by leemyongpakvn** [comment]
@kpodemski Done, as usual.

**Review by PrestaEdit — APPROVED** [review]

**Review by matks — APPROVED** [review]
Thank you @leemyongpakvn for creating the issue I move this PR to "QA testing" stage

**Comment by matks** [comment]
@leemyongpakvn I wrote a more detailed "How to test" for QA team because you described the code changes, not the usecase to use.
>  Please use productcomments module and create multiple customer reviews for products. Please then verify that the "average rating" on the front-office product page is correct: if a product received ratings 1/5 and 5/5 then the average should be 3/5

**Comment by paulnoelcholot** [comment]
Hello @leemyongpakvn, 

Thanks for your PR. The issue is well fixed and I did find any regression.

**Review by paulnoelcholot — APPROVED** [review]

**Comment by kpodemski** [comment]
Thanks @leemyongpakvn :)

**Pull request merged**
