### PR TITLE
Removed Rich Snippet Rating

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Removed Rich Snippet Rating as it is duplicated from the core (JSON-LD) : PrestaShop/PrestaShop#25551
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#25551
| How to test?  | Cf PrestaShop/Prestashop#25551

### CODE REVIEW

**Review by sowbiba — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]
Nice catch here

**Review by matks — COMMENTED** [review]
Small question asked on https://github.com/PrestaShop/PrestaShop/pull/25551#pullrequestreview-762839630
related to this PR

**Comment by florine2623** [comment]
Hello @Progi1984 ,

Thanks for the PR !
It is QA Approved : 
Screenshot 2021-09-24 at 16 55 52

Must be release with https://github.com/PrestaShop/productcomments/pull/111

Thanks !

**Comment by NeOMakinG** [comment]
Thanks @Progi1984

**Pull request merged**
